### ISSUE TITLE
[BUG] When forwarding kwargs to `shuffle` the `None` default breaks

### ISSUE THREAD

**Issue by jotterbach** [merantix-momentum/squirrel-core#143]
Using squirrel main directly from github.

When using `shuffle` inside a nested function/method, the forwarding of the `shuffle` defaults into the function does not work. According to the doc-strings ```size (int, optional): Buffer size for shuffling. Defaults to 1000. Skip the shuffle step if `size < 2`.``` so I would assume that feeding in `None` would create a default or similar. 

Test file below.

```python
import pytest
from squirrel.iterstream import IterableSource

def get_itersource():
    data = list(range(100))
    source = IterableSource(data)
    return source

@pytest.mark.parametrize('size', [None, 1, 200])
def test_1(size):

    iter = get_itersource().shuffle(size=size).collect()
    assert sorted(iter) == list(range(100))
```

**Comment by pzdkn** [comment]
I'll look into this

**Comment by pzdkn** [comment]
fixed: https://github.com/merantix-momentum/squirrel-core/pull/156
