### ISSUE TITLE
[BUG] IterableSamplerSource is not picklable

### ISSUE THREAD

**Issue by jotterbach** [merantix-momentum/squirrel-core#162]
### When reporting a bug, please be sure to include the following:
 - [x] A descriptive title
 - [x] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)

Add the following test to `test/test_iterstream/test_stream.py`

```python
@pytest.mark.parametrize("probs", [[0.4, 0.6], None])
def test_iterablesamplersource_is_picklable(probs: t.Optional[t.List[float]]) -> None:
    """Smoke test IterableSamplerSource"""
    res_1 = IterableSource([0, 1, 2, 3])
    res_2 = IterableSource([4, 5, 6])
    src = IterableSamplerSource([res_1, res_2], probs=probs)
    import pickle

    pkl = pickle.dumps(src)
    src_2 = pickle.loads(pkl)

    assert src.collect() == src_2.collect()
```

Run: `poetry run pytest -s test/test_iterstream/test_stream.py::test_iterablesamplersource_is_picklable`

 - [x] What version of `squirrel-datasets` and `squirrel` you're using, and the platform(s) you're running it on
 commit-sha: 86f61c0d403c22c9365e7ca4d37ab179acbac6dd

 - [x] What packages or other dependencies you're using
no additional packages 
 
 - [x] The behavior you expect to see and the actual behavior
 
Expected: Test passes
Actual: Fails with exception: `TypeError: cannot pickle 'generator' object`

<img width="971" alt="image" src="https://github.com/merantix-momentum/squirrel-core/assets/5595043/0578d557-e7e0-481b-a0a3-2276b0fd5930">

**Comment by jotterbach** [comment]
Picklablilty is needed when using it in a setting where you use a multi-worker torch dataloader. The torch dataloader forks the iterstream and hence every stage needs to be picklable.

**Comment by AlirezaSohofi** [comment]
Thanks a lot for the issue. This is a known limitation of `IterableSamplerSource`, The [Multiplexing](https://github.com/merantix-momentum/squirrel-core/pull/166/files) is a superset of `IterableSamplerSource`, so I'd say we can deprecate it in favour of Multiplexing. wdyt @jotterbach ?

**Comment by jotterbach** [comment]
I think this could be a workable solution @AlirezaSohofi . I didn't want to outright deprecate the `IterableSamplerSource` and hence tried to fix it in case any other code actually depends on it.

**Comment by AlirezaSohofi** [comment]
Agree, I am not suggesting to deprecate `IterableSamplerSource` right away. However I see that this api is a bit flawed, for instance it expects `iterables: List[Iterable]` while a more sensible argument would have been `iterables: List[Composable]` as in your PR. Because of this not much can be assume about the input and so not much additional functionalities can be added or guaranteed. Your change is sensible and makes this class a lot more useful, but eventually we should deprecate it and replace it by Multiplexing.
