### ISSUE TITLE
[FEATURE] Make `get_iter` method documentation about `max_workers` more explicit

### ISSUE THREAD

**Issue by kai-tub** [merantix-momentum/squirrel-core#60]
Hey, I've stumbled across a potentially easy-to-misunderstand part of the `MapDriver.get_iter` documentation:

https://github.com/merantix-momentum/squirrel-core/blob/8e2942313c7d7dd974b1ca2f2308895f660d3d26/squirrel/driver/driver.py#L68-L155

The documentation of `max_workers` states that by default `None` will be used and also _mentions_ that this will cause `async_map` to be called but I missed these parts of the documentation and was surprised to see that so many threads were allocated.

I am/was not too familiar with the `ThreadPoolExecutor` interface and find it somewhat surprising that `None` equals `numer_of_processors x 5` according to the [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) definition.
Maybe it would be helpful to explicitly state that by default ThreadPoolExecutor will be used with so many threads?
The documentation string reads a bit unintuitive as the starts out that max_worker defines how many items are fetched simultaneously with `max_worker` and then continues to state that _otherwise_ `map` is used.
From that perspective, `max_workers=None` doesn't sound like it should be using any threads at all.
Without knowing the default values of `ThreadPoolExecutor` I would make it more explicit that to _disable_ threading one has to set max_workers=0/1 and that by default _many_ threads are used.

I am happy to add a PR with my suggested doc-string update if you agree! :)

**Comment by winfried-loetzsch** [comment]
Hi @kai-tub, thank you for bringing this up! Sounds like a good step to enhance the user experience. I'd be happy to review a PR.

**Comment by winfried-loetzsch** [comment]
We should probably also mention this more explicitly in our [readthedocs](https://squirrel.readthedocs.io/en/latest/) docu, if it is not clear yet. CC @AlirezaSohofi to keep you in the loop.
